// Generated by https://quicktype.io

import 'package:flutter/cupertino.dart';

class Movies
{
  List<Movie> movieItems = new List<Movie>();

  Movies();


  //Estos métodos funcionan para llamados estáticos (?)
  Movies.fromJsonList( List<dynamic> jsonResponse )
  {
    if (jsonResponse == null)
    {
      return;
    }
    else
    {
      for (var movie in jsonResponse) {
        movie = new Movie.fromJsonMap(movie);
        movieItems.add(movie);
      }
    }
  }
}

class Movie 
{
  double popularity;
  int voteCount;
  bool video;
  String posterPath;
  int id;
  bool adult;
  String backdropPath;
  String originalLanguage;
  String originalTitle;
  List<int> genreIds;
  String title;
  double voteAverage;
  String overview;
  String releaseDate;

  Movie({
    this.popularity,
    this.voteCount,
    this.video,
    this.posterPath,
    this.id,
    this.adult,
    this.backdropPath,
    this.originalLanguage,
    this.originalTitle,
    this.genreIds,
    this.title,
    this.voteAverage,
    this.overview,
    this.releaseDate,
  });

  Movie.fromJsonMap(Map<String, dynamic> json) {
    popularity        = json["popularity"] / 1;
    voteCount         = json["vote_count"];
    video             = json["video"];
    posterPath        = json["poster_path"];
    id                = json["id"];
    adult             = json["adult"];
    backdropPath      = json["backdrop_path"];
    originalLanguage  = json["original_language"];
    originalTitle     = json["original_title"];
    //Convierte respuesta de json a List<int>
    genreIds          = json["genre_ids"].cast<int>();
    title             = json["title"];
    //Convierte int a double (en caso de números cerrados)
    voteAverage       = json["vote_average"] / 1;
    overview          = json["overview"];
    releaseDate       = json["release_date"];
  }

  NetworkImage getPosterImg()
  {
    String url;
    String defaultUrlImage = "https://image.tmdb.org/t/p/w500/";

    if ( posterPath == null)
    {
      url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdA750p7y_ICrWtWyaE7Ziyj5wKIqO-eimw6J930z8cQfBo8zr&s";
    }
    else
    {
      url = defaultUrlImage+posterPath;
    }

    return NetworkImage(url);
    
  }




}
